spring:
  kafka.producer.transaction-id-prefix: txDummy.
  cloud:
    stream:
      bindings:
        input:
          group: input
          destination: kafka_retry_store
#          consumer:
#            back-off-initial-interval: 500
#            back-off-max-interval: 5000
#            max-attempts: 1
      kafka:
        binder:
          configuration:
            auto.offset.reset: earliest
          headers: x-retries 
          transaction:
            transaction-id-prefix: txKafkaStreamRetry2.
            producer:
              configuration:
                acks: all
                retries: 10        
        bindings:
          input:
            consumer:
              ack-each-record: true
              enable-dlq: false
              auto-commit-offset: true
              auto-commit-on-error: false
              
info.component: Kafka Retry Service

server.port: ${SERVER_PORT:9082}

management.server.port: ${MANAGEMENT_SERVER_PORT:9083}
